TYPE_FUNCTION = 'FN'
TYPE_RETURN_CURSOR = 'cursor'
TYPE_RETURN_NUMBER = 'numeric'
TYPE_RETURN_STRING = 'string'
SUCCESS_CODE = 'UPX200'
SUCCESS_MESSAGE = 'Ok'
ERROR_CODE = 'UPX500'
COMMERCIAL_ADDRESS_TYPE = '1'
FISCAL_ADDRESS_TYPE = '2'
PRIORITY_ITEM = 71
REGISTER_ITEM = 70
ZERO = 0
IMPUTABLE = 'UPAXER'

AWS_REGION = 'us-east-1'
SECRETS_MANAGER = 'secretsmanager'